parcelRequire=function(e,r,t,n){var i,o="function"==typeof parcelRequire&&parcelRequire,u="function"==typeof require&&require;function f(t,n){if(!r[t]){if(!e[t]){var i="function"==typeof parcelRequire&&parcelRequire;if(!n&&i)return i(t,!0);if(o)return o(t,!0);if(u&&"string"==typeof t)return u(t);var c=new Error("Cannot find module '"+t+"'");throw c.code="MODULE_NOT_FOUND",c}p.resolve=function(r){return e[t][1][r]||r},p.cache={};var l=r[t]=new f.Module(t);e[t][0].call(l.exports,p,l,l.exports,this)}return r[t].exports;function p(e){return f(p.resolve(e))}}f.isParcelRequire=!0,f.Module=function(e){this.id=e,this.bundle=f,this.exports={}},f.modules=e,f.cache=r,f.parent=o,f.register=function(r,t){e[r]=[function(e,r){r.exports=t},{}]};for(var c=0;c<t.length;c++)try{f(t[c])}catch(e){i||(i=e)}if(t.length){var l=f(t[t.length-1]);"object"==typeof exports&&"undefined"!=typeof module?module.exports=l:"function"==typeof define&&define.amd?define(function(){return l}):n&&(this[n]=l)}if(parcelRequire=f,i)throw i;return f}({"Zy0T":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.galleryItems=void 0;var p=[{preview:"https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/16/43/himilayan-blue-poppy-4202825_1280.jpg",description:"Hokkaido Flower"},{preview:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/14/22/05/container-4203677_1280.jpg",description:"Container Haulage Freight"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/09/47/beach-4206785_1280.jpg",description:"Aerial Beach View"},{preview:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619__340.jpg",original:"https://cdn.pixabay.com/photo/2016/11/18/16/19/flowers-1835619_1280.jpg",description:"Flower Blooms"},{preview:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334__340.jpg",original:"https://cdn.pixabay.com/photo/2018/09/13/10/36/mountains-3674334_1280.jpg",description:"Alpine Mountains"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/23/04/landscape-4208571_1280.jpg",description:"Mountain Lake Sailing"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/09/27/the-alps-4209272_1280.jpg",description:"Alpine Spring Meadows"},{preview:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/16/21/10/landscape-4208255_1280.jpg",description:"Nature Landscape"},{preview:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843__340.jpg",original:"https://cdn.pixabay.com/photo/2019/05/17/04/35/lighthouse-4208843_1280.jpg",description:"Lighthouse Coast Sea"}];exports.galleryItems=p;
},{}],"tW6H":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.marcup=void 0;var e=function(e,r){var a=e.map(function(e){return'<li class="gallery__item"><a class="gallery__link"><img class="gallery__image" \n        src="'.concat(e.preview,'" alt="').concat(e.description,'"></a></li>')}).join("");return r.insertAdjacentHTML("afterbegin",a)};exports.marcup=e;
},{}],"JN7f":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.overlay=exports.modalButton=exports.lightbox=exports.gallery=exports.bigImage=void 0;var e=document.querySelector(".js-gallery");exports.gallery=e;var o=document.querySelector(".js-lightbox");exports.lightbox=o;var t=document.querySelector(".lightbox__image");exports.bigImage=t;var r=document.querySelector('button[data-action="close-lightbox"]');exports.modalButton=r;var l=document.querySelector(".lightbox__overlay");exports.overlay=l;
},{}],"Vhh2":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.openOrCloseModal=void 0;var e=require("./consts"),o=function(){e.lightbox.classList.toggle("is-open")};exports.openOrCloseModal=o;
},{"./consts":"JN7f"}],"dLA0":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.setPictureAtribute=void 0;var e=require("./consts"),t=require("./openOrCloseModal"),r=function(r){e.bigImage.setAttribute("src",r.original),e.bigImage.setAttribute("alt",r.description),(0,t.openOrCloseModal)()};exports.setPictureAtribute=r;
},{"./consts":"JN7f","./openOrCloseModal":"Vhh2"}],"HFI6":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.findTarget=void 0;var e=require("./setPictureAtribute"),t=require("./list"),r=function(r){r.preventDefault();var i=r.target;if("IMG"===i.nodeName){var u=i.getAttribute("src"),n=t.galleryItems.find(function(e){return u===e.preview});(0,e.setPictureAtribute)(n)}};exports.findTarget=r;
},{"./setPictureAtribute":"dLA0","./list":"Zy0T"}],"eo33":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.removePictureAtribute=void 0;var e=require("./consts"),t=require("./openOrCloseModal"),r=function(){(0,t.openOrCloseModal)(),e.bigImage.setAttribute("src",""),e.bigImage.setAttribute("alt","")};exports.removePictureAtribute=r;
},{"./consts":"JN7f","./openOrCloseModal":"Vhh2"}],"BOTC":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.closeModalWithEscape=void 0;var e=require("./removePictureAtribute"),t=function(t){"Escape"===t.key&&(0,e.removePictureAtribute)()};exports.closeModalWithEscape=t;
},{"./removePictureAtribute":"eo33"}],"atWa":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.findCurrentElementIndex=void 0;var e=require("./consts"),r=require("./list"),t=function(){var t=r.galleryItems.find(function(r){return e.bigImage.getAttribute("src")===r.original});return r.galleryItems.indexOf(t)};exports.findCurrentElementIndex=t;
},{"./consts":"JN7f","./list":"Zy0T"}],"WYo6":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.openPreviousImage=void 0;var e=require("./consts"),t=require("./list"),r=function(r){e.bigImage.setAttribute("src",t.galleryItems[r-1].original),e.bigImage.setAttribute("alt",t.galleryItems[r-1].description)};exports.openPreviousImage=r;
},{"./consts":"JN7f","./list":"Zy0T"}],"XQi0":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.openNextImage=void 0;var e=require("./consts"),t=require("./list"),r=function(r){e.bigImage.setAttribute("src",t.galleryItems[r+1].original),e.bigImage.setAttribute("alt",t.galleryItems[r+1].description)};exports.openNextImage=r;
},{"./consts":"JN7f","./list":"Zy0T"}],"kUMP":[function(require,module,exports) {
"use strict";Object.defineProperty(exports,"__esModule",{value:!0}),exports.openNextOrPreviousImage=void 0;var e=require("./list"),r=require("./findCurrentElementIndex"),t=require("./openPreviousImage"),o=require("./openNextImage"),n=function(n){var i=(0,r.findCurrentElementIndex)();"ArrowLeft"===n.key&&i>0?(0,t.openPreviousImage)(i):"ArrowRight"===n.key&&i<e.galleryItems.length-1&&(0,o.openNextImage)(i)};exports.openNextOrPreviousImage=n;
},{"./list":"Zy0T","./findCurrentElementIndex":"atWa","./openPreviousImage":"WYo6","./openNextImage":"XQi0"}],"mpVp":[function(require,module,exports) {
"use strict";var e=require("./js/list"),r=require("./js/markup"),t=require("./js/consts"),i=require("./js/delegation"),s=require("./js/removePictureAtribute"),a=require("./js/closeModalWithEscape"),n=require("./js/openNextOrPreviousImage");(0,r.marcup)(e.galleryItems,t.gallery),t.gallery.addEventListener("click",i.findTarget),t.modalButton.addEventListener("click",s.removePictureAtribute),t.overlay.addEventListener("click",s.removePictureAtribute),window.addEventListener("keydown",a.closeModalWithEscape),window.addEventListener("keydown",n.openNextOrPreviousImage);
},{"./js/list":"Zy0T","./js/markup":"tW6H","./js/consts":"JN7f","./js/delegation":"HFI6","./js/removePictureAtribute":"eo33","./js/closeModalWithEscape":"BOTC","./js/openNextOrPreviousImage":"kUMP"}]},{},["mpVp"], null)
//# sourceMappingURL=/gallery/script.js.map